Repository brain-tec/odoo-pim, pull requests merged in 2022-04, with the labels that each got.

#39 Syncing from upstream OCA/odoo-pim (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  attribute_set/models/attribute_attribute.py
Labels: 14.0

#40 Syncing from upstream OCA/odoo-pim (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#42 [t128770] Fix error on smart button to check variants.
  product_attribute_set/views/product.xml
Labels: bug, 15.0.project_ge_578

#43 Syncing from upstream OCA/odoo-pim (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: 13.0

#44 [t127823] Applying GE inheritance on products:
  attribute_set/models/attribute_set_owner.py
  product_attribute_set/models/product.py
Labels: 15.0.project_ge_578
